version: '2'
volumes:
  data1:
    driver: local

services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "9880:9880"

  elasticsearch:
    build: ./elastic
    environment:
      - "ES_JAVA_OPTS: -Xms384m -Xmx384m"
#      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data1:/usr/share/elasticsearch/data
    expose:
      - 9200
    ports:
      - "9200:9200"
      - "9300:9300"

  curator:
    build: curator/
    links:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      MAX_INDEX_AGE: 1

  kibana:
    image: kibana:5.5
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
